//! Graf → `visual_blueprint!` DSL matni (editor eksporti).

use crate::ast::VisualScriptGraph;
use crate::nodes::NodeKind;
use crate::validate::validate_graph;

/// Validatsiyadan o‘tgan grafni makro DSL qatoriga aylantiradi.
pub fn graph_to_dsl(graph: &VisualScriptGraph) -> Result<String, String> {
    validate_graph(graph).map_err(|e| e.message)?;

    let entry = graph.begin_play_entry()?;
    let mut body = String::new();
    emit_exec_node(graph, entry, &mut body, true)?;

    Ok(format!(
        "// Auto-generated by twelfth_editor — do not edit by hand.\n\
         // Rebuild: cargo run -p twelfth_editor_play\n\n\
         use visual_blueprint_macros::visual_blueprint;\n\n\
         visual_blueprint! {{\n\
             script EditorGeneratedPlugin;\n\
             startup {{\n\
{body}\
             }}\n\
         }}\n"
    ))
}

fn emit_exec_node(
    graph: &VisualScriptGraph,
    node_id: usize,
    out: &mut String,
    is_entry: bool,
) -> Result<(), String> {
    let node = graph
        .node(node_id)
        .ok_or_else(|| format!("tugun #{node_id} topilmadi"))?;

    match &node.kind {
        NodeKind::EventBeginPlay | NodeKind::EventTick => {
            if let Some(next) = graph.exec_successors(node_id, "exec_out").first() {
                emit_exec_node(graph, *next, out, false)?;
            }
        }
        NodeKind::CheckGoldAmount => {
            let threshold = node.gold_threshold.unwrap_or(0.0);
            let var = format!("n{node_id}");
            out.push_str(&format!("        let {var} = check_gold {threshold};\n"));
            if let Some(next) = graph.exec_successors(node_id, "exec_out").first() {
                emit_exec_node_after_check(graph, *next, out, &var)?;
            }
        }
        NodeKind::Branch => {
            let cond = graph
                .data_source(node_id, "condition")
                .map(|p| format!("n{}", p.node_id))
                .unwrap_or_else(|| {
                    if node.condition_value.unwrap_or(false) {
                        "true".to_string()
                    } else {
                        "false".to_string()
                    }
                });
            out.push_str(&format!("        branch {cond} {{\n"));
            emit_branch_arm(graph, node_id, "true", "arm_true", out)?;
            emit_branch_arm(graph, node_id, "false", "arm_false", out)?;
            out.push_str("        }\n");
        }
        NodeKind::PrintLog => {
            let msg = node
                .log_message
                .as_deref()
                .unwrap_or("log");
            let escaped = msg.replace('\\', "\\\\").replace('"', "\\\"");
            out.push_str(&format!("        log \"{escaped}\";\n"));
            if !is_entry {
                if let Some(next) = graph.exec_successors(node_id, "exec_out").first() {
                    emit_exec_node(graph, *next, out, false)?;
                }
            }
        }
        NodeKind::AddGold => {
            let amount = node.gold_amount.unwrap_or(0.0);
            out.push_str(&format!("        add_gold {amount};\n"));
            if let Some(next) = graph.exec_successors(node_id, "exec_out").first() {
                emit_exec_node(graph, *next, out, false)?;
            }
        }
        NodeKind::Delay => {
            return Err(format!(
                "Delay (#{node_id}) hali DSL eksport qilinmadi — faqat kanvasda ishlatiladi"
            ));
        }
        // Entity exec nodes
        NodeKind::SpawnEntity | NodeKind::DestroyEntity
        | NodeKind::SetTranslation | NodeKind::Translate
        | NodeKind::SetScale | NodeKind::SetRotationEuler => {
            // Pass-through: downstream zanjirini ishga tushiradi
            if let Some(next) = graph.exec_successors(node_id, "exec_out").first() {
                emit_exec_node(graph, *next, out, false)?;
            }
        }
        NodeKind::EventCustomBegin => {
            if let Some(next) = graph.exec_successors(node_id, "exec_out").first() {
                emit_exec_node(graph, *next, out, false)?;
            }
        }
        NodeKind::FireCustomEvent => {
            let name = node.event_name.as_deref().unwrap_or("unknown");
            out.push_str(&format!("        // fire_event \"{name}\" (DSL chiqarilmadi);\n"));
            if let Some(next) = graph.exec_successors(node_id, "exec_out").first() {
                emit_exec_node(graph, *next, out, false)?;
            }
        }
        // Pure math/logic nodes (Float*, Bool*, Vec3*, String*, Int*, Entity-pure) have no exec flow —
        // they should never appear as direct exec-chain entries.
        kind => {
            return Err(format!(
                "Tugun #{node_id} ({kind:?}) exec oqimida bo'lishi kutilmagan — pure tugun"
            ));
        }
    }
    Ok(())
}

fn emit_exec_node_after_check(
    graph: &VisualScriptGraph,
    node_id: usize,
    out: &mut String,
    check_var: &str,
) -> Result<(), String> {
    let node = graph.node(node_id).ok_or_else(|| format!("#{node_id}"))?;
    if node.kind == NodeKind::Branch {
        out.push_str(&format!("        branch {check_var} {{\n"));
        emit_branch_arm(graph, node_id, "true", "arm_true", out)?;
        emit_branch_arm(graph, node_id, "false", "arm_false", out)?;
        out.push_str("        }\n");
        return Ok(());
    }
    emit_exec_node(graph, node_id, out, false)
}

fn emit_branch_arm(
    graph: &VisualScriptGraph,
    branch_id: usize,
    pin: &str,
    dsl_kw: &str,
    out: &mut String,
) -> Result<(), String> {
    out.push_str(&format!("            {dsl_kw} {{\n"));
    for child in graph.exec_successors(branch_id, pin) {
        let node = graph.node(child).ok_or_else(|| format!("#{child}"))?;
        match &node.kind {
            NodeKind::PrintLog => {
                let msg = node.log_message.as_deref().unwrap_or("log");
                let escaped = msg.replace('\\', "\\\\").replace('"', "\\\"");
                out.push_str(&format!("                log \"{escaped}\";\n"));
            }
            NodeKind::AddGold => {
                let amount = node.gold_amount.unwrap_or(0.0);
                out.push_str(&format!("                add_gold {amount};\n"));
            }
            other => {
                return Err(format!(
                    "Branch shoxida {:?} hali DSL eksport qilinmadi",
                    other
                ));
            }
        }
    }
    out.push_str("            }\n");
    Ok(())
}
